name: Deploy

on:
  workflow_run:
    workflows: ["UI Tests"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy to Render.com
    runs-on: ubuntu-latest
  
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID }}
          api-key: ${{ secrets.RENDER_TOKEN }}
