name: UI Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Build App
      run: npm ci
    - name: Install Playwrigth
      run: npx playwright install
    - name: Start server
      run: node ./server/server.js &
    - name: Start App
      run: npm start &
    - name: Run tests
      run: npm run testUi